### ISSUE TITLE
Res.redirect is not a function

### ISSUE THREAD

**Issue by domsteil** [bluebeel/nextjs-shopify-auth#6]
I am not able to get to the auth redirect.

[GET] /api/shopify/auth/inline?shop={shopName}
10:39:10:76
2021-02-17T18:39:10.830Z	daf12db1-9f18-43d7-b793-b54ab871dea9	ERROR	TypeError: res.redirect is not a function
    at oAuthStart (/var/task/node_modules/@bluebeela/nextjs-shopify-auth/dist/auth/create-oauth-start.js:25:13)
    at shopifyAuthInline (/var/task/.next/serverless/pages/api/shopify/auth/inline.js:268:9)
    at apiResolver (/var/task/node_modules/next/dist/next-server/server/api-utils.js:46:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports.COyd.__webpack_exports__.default (/var/task/.next/serverless/pages/api/shopify/auth/inline.js:187:11)

**Comment by bluebeel** [comment]
Can you give me a full context. What step did you do to get this error?

**Comment by domsteil** [comment]
I get this error when it is trying to authenticate with the shop parameter. It then falls back to /login
